services:
  - type: web
    name: setu-backend
    env: docker
    dockerContext: .
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0

  - type: web
    name: setu-backend-core
    env: node
    rootDir: backend-core
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_VERSION
        value: 20.x
